homework_final/vacations/claims/urls.py
from django.urls import path

import claims.views as claims

app_name = 'claims'

urlpatterns = [
    path('detail/<int:pk>/', claims.ClaimDetailView.as_view(), name='detail'),
    path('create/', claims.ClaimCreateView.as_view(), name='create'),
    path('update/<int:pk>/', claims.ClaimUpdateView.as_view(), name='update'),
    path('accept/<int:pk>/', claims.accept_claim, name='accept_claim'),
    path('reject/<int:pk>/', claims.reject_claim, name='reject_claim'),
]

homework_final/vacations/myauth/urls.py
import myauth.views as myauth
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = 'myauth'

urlpatterns = [
    path('register/', myauth.EmployeeCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

homework_final/vacations/vacations/urls.py
import claims.views as claims
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', claims.HomePageView.as_view(), name='main'),
    path('cabinet/', claims.ClaimListView.as_view(), name='claim_list'),
    path('approve/', claims.ClaimApproveListView.as_view(), name='claim_approve_list'),
    path('approve/detail/<int:pk>/', claims.ClaimApproveDetailView.as_view(), name='claim_approve_detail'),
    path('claim/', include('claims.urls', namespace='claims')),
    path('myauth/', include('myauth.urls', namespace='myauth')),

    path('admin/', admin.site.urls),
]

homework_final/vacations/claims/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Claim(models.Model):
    class ClaimType(models.TextChoices):
        MAIN = 'MN', _('Основной')
        ADDITIONAL = 'AD', _('Дополнительный')
        CHILD = 'CH', _('По уходу за ребёнком')
        NOTPAID = 'NP', _('Не оплачиваемый')
        STUDY = 'ST', _('На учёбу')

    class ClaimStatus(models.TextChoices):
        ON_APPROVAL = 'OA', _('На согласовании')
        REJECTED = 'RE', _('Отклонено')
        ACCEPTED = 'AC', _('Согласовано')

    type = models.CharField(
        max_length=2,
        choices=ClaimType.choices,
        default=ClaimType.MAIN,
        verbose_name='Тип отпуска'
    )

    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Дата конца')
    is_pay_now = models.BooleanField(verbose_name='Выплатить отпускные сейчас')
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    employee = models.ForeignKey('myauth.Employee', related_name='employee', on_delete=models.CASCADE,
                                 verbose_name='Сотрудник')
    agreed_with = models.ForeignKey('myauth.Employee', related_name='manager', on_delete=models.CASCADE,
                                    verbose_name='Руководитель')

    status = models.CharField(
        max_length=2,
        choices=ClaimStatus.choices,
        default=ClaimStatus.ON_APPROVAL,
        blank=True,
        verbose_name='Статус'
    )

    def __str__(self):
        return f"Заявление #{self.pk} от {self.employee.get_short_fio()} " \
               f"({self.start_date} – {self.start_date}) " \
               f"– {self.ClaimStatus(self.status).label}"

    def get_status(self):
        return self.ClaimStatus(self.status).label

    def get_type(self):
        return self.ClaimType(self.type).label

homework_final/vacations/claims/forms.py
from claims.models import Claim
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit, Button, Field
from django.core.exceptions import ValidationError
from django.forms import ModelForm, DateInput


class ClaimCreateForm(ModelForm):
    class Meta:
        model = Claim
        fields = '__all__'
        exclude = ('employee',)
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        super(ClaimCreateForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('type', css_class='col-md-8 mb-0'),
            Row(
                Column('start_date', css_class='form-group col-md-4 mb-0'),
                Column('end_date', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Field('is_pay_now', css_class='col-md-8 mb-0'),
            Field('agreed_with', css_class='col-md-8 mb-0'),
            Field('comment', css_class='col-md-8 mb-0', rows='2'),
            Field('status', css_class='col-md-8 mb-0', disabled=True, value="OA"),
            FormActions(
                Submit('save', 'Отправить'),
                Button('cancel', 'Отменить', onclick="javascript:history.back();")
            )
        )

    def clean(self):
        cleaned_data = super(ClaimCreateForm, self).clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        if start_date and end_date:
            if end_date < start_date:
                raise ValidationError("Дата окончания должна быть позже даты начала отпуска")
        return cleaned_data

    def save(self, commit=True):
        self.instance.employee = self._user
        return super().save(commit)


class ClaimUpdateForm(ModelForm):
    class Meta:
        model = Claim
        fields = '__all__'
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('employee', css_class='col-md-8 mb-0', disabled=True),
            Field('type', css_class='col-md-8 mb-0'),
            Row(
                Column('start_date', css_class='form-group col-md-4 mb-0'),
                Column('end_date', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Field('is_pay_now', css_class='col-md-8 mb-0'),
            Field('agreed_with', css_class='col-md-8 mb-0'),
            Field('comment', css_class='col-md-8 mb-0', rows='2'),
            Field('status', css_class='col-md-8 mb-0', disabled=True),
            FormActions(
                Submit('save', 'Сохранить'),
                Button('cancel', 'Отменить', onclick="javascript:history.back();")
            )
        )

homework_final/vacations/claims/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, TemplateView
from django.views.generic.base import ContextMixin

from .forms import ClaimCreateForm, ClaimUpdateForm
from .models import Claim


def accept_claim(request, pk):
    Claim.objects.filter(pk=pk).update(status=Claim.ClaimStatus.ACCEPTED)
    return redirect('claim_approve_list')


def reject_claim(request, pk):
    Claim.objects.filter(pk=pk).update(status=Claim.ClaimStatus.REJECTED)
    return redirect('claim_approve_list')


class PageNameMixin(ContextMixin):
    page_name = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['page_title'] = self.page_name
        context['page_header'] = self.page_name
        return context


class HomePageView(PageNameMixin, TemplateView):
    template_name = "claims/home.html"


class ClaimDetailView(LoginRequiredMixin, PageNameMixin, DetailView):
    model = Claim
    page_name = 'Заявление'


class ClaimListView(LoginRequiredMixin, PageNameMixin, ListView):
    model = Claim
    page_name = 'Мои заявления'
    context_object_name = 'claims'
    paginate_by = 15

    def get_queryset(self):
        return Claim.objects.filter(employee=self.request.user)


class ClaimApproveListView(LoginRequiredMixin, PageNameMixin, ListView):
    model = Claim
    page_name = 'Мои задания'
    context_object_name = 'claims'
    paginate_by = 15
    template_name = 'claims/claim_approve_list.html'
    body_size = 'col-10'

    def get_queryset(self):
        return Claim.objects.filter(agreed_with=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['body_size'] = self.body_size
        return context


class ClaimApproveDetailView(LoginRequiredMixin, PageNameMixin, DetailView):
    model = Claim
    page_name = 'Заявление'
    template_name = 'claims/claim_approve_detail.html'


class ClaimCreateView(LoginRequiredMixin, PageNameMixin, CreateView):
    model = Claim
    page_name = 'Новое заявление'
    success_url = reverse_lazy('claim_list')
    form_class = ClaimCreateForm

    def get_form_kwargs(self):
        kwargs = super(ClaimCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class ClaimUpdateView(LoginRequiredMixin, PageNameMixin, UpdateView):
    model = Claim
    page_name = 'Редактирование заявления'
    success_url = reverse_lazy('claim_list')
    form_class = ClaimUpdateForm

homework_final/vacations/claims/templates/claims/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css"
          rel="stylesheet">
    <title>{{ page_title|default:"Отпуска" }}</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <ul class="nav justify-content-left" class="col-8">
                <li class="nav-item">
                    <a class="nav-link active icon-home" href="{% url 'main' %}">🌴</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'claim_list' %}">Мои заявления</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'claim_approve_list' %}">Мои задания</a>
                </li>
                <li class="nav-item">
                    {% if user.is_anonymous %}
                    <a class="nav-link" href="{% url 'myauth:login' %}">Войти</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'myauth:logout' %}">Выйти</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="{{ body_size|default:'col-8' }}">
            <h1>
                {% block header %}
                {{ page_header|default:"Отпуска" }}
                {% endblock %}
            </h1>
            <hr class="mt-0 mb-4">
            {% block main_content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

homework_final/vacations/claims/templates/claims/claim_approve_detail.html
{% extends 'claims/base.html' %}

{% block header %}
Заявление #{{ claim.pk }}
{% endblock %}

{% block main_content %}
<table class="table table-borderless">
    <tbody>
    <tr>
        <td>
            Сотрудник
        </td>
        <td>
            {{ claim.employee.get_full_fio}}
        </td>
    </tr>
    <tr>
        <td>
            Тип отпуска
        </td>
        <td>
            {{ claim.get_type }}
        </td>
    </tr>
    <tr>
        <td>
            Период отпуска
        </td>
        <td>
            {{ claim.start_date|date:'d.m.yy' }} – {{ claim.end_date|date:'d.m.yy' }}
        </td>
    </tr>
    <tr>
        <td>
            Статус
        </td>
        <td>
            {{ claim.get_status }}
        </td>
    </tr>
    <tr>
        <td>
            Выплатить отпускные сейчас
        </td>
        <td>
            {% if claim.is_pay_now %}
            Да
            {% else %}
            Нет
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Руководитель
        </td>
        <td>
            {{ claim.agreed_with.get_full_fio}}
        </td>
    </tr>
    <tr>
        <td>
            Комментарий
        </td>
        <td>
            {{ claim.comment}}
        </td>
    </tr>
    </tbody>
</table>
<table>
    <tbody>
    <tr>
        <td>
            <form method="post" action="{% url 'claims:accept_claim' pk=claim.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Согласовать</button>
            </form>
        </td>
        <td>
            <form method="post" action="{% url 'claims:reject_claim' pk=claim.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Отклонить</button>
            </form>
        </td>
        <td>
            <a class="btn btn-outline-secondary" href="{% url 'claim_approve_list' %}" role="button">Вернуться к моим
                заданиям</a>
        </td>
    <tr>
    </tbody>
</table>
{% endblock %}

homework_final/vacations/claims/templates/claims/claim_approve_list.html
{% extends 'claims/base.html' %}

{% block main_content %}
{% if claims %}
<table class="table table-borderless table-hover">
    <thead>
    <tr>
        <th>Заявление</th>
        <th>Период</th>
        <th>Сотрудник</th>
        <th>Статус</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for element in claims %}
    <tr>
        <td>
            <a href="{% url 'claim_approve_detail' pk=element.pk %}">
                Заявление #{{ element.pk }}
            </a>
            <br/>
        </td>
        <td>
            {{ element.start_date|date:'d.m.yy' }} – {{ element.end_date|date:'d.m.yy' }}
        </td>
        <td>
            {{ element.employee.get_short_fio }}
        </td>
        {% if element.status == "RE" %}
        <td style="color:red">
            {{ element.get_status }}
        </td>
        {% elif element.status == "AC" %}
        <td style="color:green">
            {{ element.get_status }}
        </td>
        {% else %}
        <td>
            {{ element.get_status }}
        </td>
        {% endif %}
        {% if element.status == "OA" %}
        <td>
            <form method="post" action="{% url 'claims:accept_claim' pk=element.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Согласовать</button>
            </form>
        </td>
        <td>
            <form method="post" action="{% url 'claims:reject_claim' pk=element.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Отклонить</button>
            </form>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Все задания выполнены.</p>
{% endif %}
{% endblock %}

homework_final/vacations/claims/templates/claims/claim_detail.html
{% extends 'claims/base.html' %}

{% block header %}
Заявление #{{ claim.pk }}
{% endblock %}

{% block main_content %}
<table class="table table-borderless">
    <tbody>
    <tr>
        <td>
            Сотрудник
        </td>
        <td>
            {{ claim.employee.get_full_fio}}
        </td>
    </tr>
    <tr>
        <td>
            Тип отпуска
        </td>
        <td>
            {{ claim.get_type }}
        </td>
    </tr>
    <tr>
        <td>
            Период отпуска
        </td>
        <td>
            {{ claim.start_date|date:'d.m.yy' }} – {{ claim.end_date|date:'d.m.yy' }}
        </td>
    </tr>
    <tr>
        <td>
            Статус
        </td>
        <td>
            {{ claim.get_status }}
        </td>
    </tr>
    <tr>
        <td>
            Выплатить отпускные сейчас
        </td>
        <td>
            {% if claim.is_pay_now %}
            Да
            {% else %}
            Нет
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Руководитель
        </td>
        <td>
            {{ claim.agreed_with.get_full_fio}}
        </td>
    </tr>
    <tr>
        <td>
            Комментарий
        </td>
        <td>
            {{ claim.comment}}
        </td>
    </tr>
    </tbody>
</table>
<a class="btn btn-primary" href="{% url 'claims:update' pk=claim.pk %}" role="button">Редактировать</a>
<a class="btn btn-outline-secondary" href="{% url 'claim_list' %}" role="button">Вернуться к списку отпусков</a>
{% endblock %}

homework_final/vacations/claims/templates/claims/claim_form.html
{% extends 'claims/base.html' %}

{% load crispy_forms_tags %}

{% block main_content %}
<form method="post">
    <p>Cотрудник: {{ user.get_full_fio }}</p>
    <p>Должность: {{ user.position }}</p>
    {% csrf_token %}
    {% crispy form %}
    {{ form.media }}
</form>
{% endblock %}

homework_final/vacations/claims/templates/claims/claim_list.html
{% extends 'claims/base.html' %}

{% block main_content %}
{% if claims %}
<a class="btn btn-primary" href="{% url 'claims:create' %}" role="button">+ Создать заявление</a>
<table class="table table-borderless table-hover">
    <thead>
    <tr>
        <th>Заявление</th>
        <th>Дата</th>
        <th>Сотрудник</th>
        <th>Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for element in claims %}
    <tr>
        <td>
            <a href="{% url 'claims:detail' pk=element.pk %}">
                Заявление #{{ element.pk }}
            </a>
        </td>
        <td>
            {{ element.start_date|date:'d.m.yy' }} – {{ element.end_date|date:'d.m.yy' }}
        </td>
        <td>
            {{ element.employee.get_short_fio }}
        </td>
        {% if element.status == "RE" %}
        <td style="color:red">
            {{ element.get_status }}
        </td>
        {% elif element.status == "AC" %}
        <td style="color:green">
            {{ element.get_status }}
        </td>
        {% else %}
        <td>
            {{ element.get_status }}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
<p>
    {% if is_paginated %}
    {% if page_obj.has_previous %}
    <a href="{% url 'claim_list' %}?page={{ page_obj.previous_page_number }}">&laquo;</a>
    {% endif %}

    <span class="page-current">
                 страница {{ page_obj.number }} из {{ page_obj.paginator.num_page }}

            </span>

    {% if page_obj.has_next %}
    <a href="{% url 'claim_list' %}?page={{ page_obj.next_page_number }}">&raquo;</a>
    {% endif %}
    {% endif %}
</p>
{% else %}
<p>У вас пока нет заявлений.</p>
<a class="btn btn-primary" href="{% url 'claims:create' %}" role="button">+ Создать заявление</a>
{% endif %}
{% endblock %}

homework_final/vacations/claims/templates/claims/home.html
{% extends 'claims/base.html' %}

{% block main_content %}
<p>
    Добро пожаловать в сервис Отпуска! Вы можете создать заявление на отпуск, согласовать со своим руководителем,
    просмотреть прошлые заявление на отпуск.
</p>
<div class="text-center">

    <img class="img-fluid rounded m-4 text-center"
         src="https://grodnonews.by/upload/iblock/e00/e0002fa588982fec33551664c5cc19d0.jpg">
    <p>
        Ну что, поехали в отпуск?
    </p>

    <a class="btn btn-primary" href="{% url 'claims:create' %}" role="button">+ Создать заявление</a>
</div>
{% endblock %}